-- ---------------------------------------------------------------------------
-- V1__usuarios.sql — la tabla `usuario` de usuarios_db (data-model.md).
--
-- El esquema lo versiona Flyway, no Hibernate: `ddl-auto: validate` solo
-- compara el mapeo de UserEntity contra lo que hay aquí, y el servicio se
-- niega a arrancar si divergen.
-- ---------------------------------------------------------------------------

CREATE TABLE usuario (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(60)  NOT NULL,
    nombre        varchar(120) NOT NULL,
    -- BCrypt produce siempre 60 caracteres; 72 deja margen sin invitar a
    -- guardar nunca la contraseña en claro.
    password_hash varchar(72)  NOT NULL,
    rol           varchar(20)  NOT NULL,
    activo        boolean      NOT NULL DEFAULT true,
    creado_en     timestamp    NOT NULL DEFAULT now(),

    -- Enumeración cerrada (R-001). La base rechaza un rol inventado aunque el
    -- código lo dejara pasar.
    CONSTRAINT usuario_rol_valido CHECK (rol IN ('USUARIO_FINAL', 'ADMINISTRADOR'))
);

-- FR-002: el username identifica la cuenta. El índice único es lo que hace que
-- el duplicado sea imposible, no solo improbable.
CREATE UNIQUE INDEX usuario_username_unico ON usuario (username);
