-- ---------------------------------------------------------------------------
-- V1__canchas.sql — el catálogo de canchas_db (data-model.md).
--
-- Las dos tablas van juntas desde la primera migración, como fija data-model.md:
-- `bloqueo_mantenimiento` no tiene entidad JPA todavía (la administración de
-- bloqueos llega con US2), y `ddl-auto: validate` no se queja de una tabla que
-- ningún mapeo reclama. Partir el esquema en dos migraciones solo por el orden
-- en que se construyen las pantallas complicaría el historial sin ganar nada.
-- ---------------------------------------------------------------------------

CREATE TABLE cancha (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(120) NOT NULL,
    deporte       varchar(20)  NOT NULL,
    hora_apertura time         NOT NULL,
    hora_cierre   time         NOT NULL,
    activa        boolean      NOT NULL DEFAULT true,

    -- Enumeración cerrada (R-008). "Fútbol" no está en el alcance, y la base lo
    -- rechaza aunque el código lo dejara pasar.
    CONSTRAINT cancha_deporte_valido CHECK (deporte IN ('PADEL', 'TENIS', 'BASQUET')),

    -- RN-07: un horario que cierra antes de abrir no delimita ningún bloque, y
    -- dejaría la disponibilidad calculando sobre un rango vacío o invertido.
    CONSTRAINT cancha_horario_valido CHECK (hora_cierre > hora_apertura)
);

CREATE TABLE bloqueo_mantenimiento (
    id        bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id bigint       NOT NULL REFERENCES cancha (id),
    desde     timestamp    NOT NULL,
    hasta     timestamp    NOT NULL,
    motivo    varchar(200),

    CONSTRAINT bloqueo_rango_valido CHECK (hasta > desde)
);

-- La disponibilidad y los reportes consultan siempre por cancha.
CREATE INDEX bloqueo_por_cancha ON bloqueo_mantenimiento (cancha_id, desde);
