-- ---------------------------------------------------------------------------
-- V1__reservas.sql — la tabla que sostiene RN-01 a RN-06 y RN-08.
--
-- **Sin claves foráneas hacia cancha ni usuario**, y no es una omisión: son
-- entidades de otras bases, a las que esta conexión no llega (Principio IV).
-- Que la cancha existe, está activa y el bloque cae dentro de su horario lo
-- valida BookingService llamando a ms-canchas por CourtClientPort, antes de
-- persistir.
-- ---------------------------------------------------------------------------

CREATE TABLE reserva (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id   bigint      NOT NULL,
    usuario_id  bigint      NOT NULL,
    fecha       date        NOT NULL,
    hora_inicio time        NOT NULL,
    hora_fin    time        NOT NULL,
    estado      varchar(20) NOT NULL,
    creada_en   timestamp   NOT NULL DEFAULT now(),
    cancelada_en timestamp,

    CONSTRAINT reserva_estado_valido CHECK (estado IN ('CONFIRMADA', 'CANCELADA', 'FINALIZADA')),
    CONSTRAINT reserva_bloque_valido CHECK (hora_fin > hora_inicio)
);

-- --- RN-02, en la base ------------------------------------------------------
--
-- La comprobación previa de BookingService da el mensaje claro en el caso
-- normal. Esta restricción cubre el caso que ninguna comprobación previa puede
-- cubrir: dos transacciones que comprueban a la vez y ambas ven el bloque
-- libre. Es lo que mide SC-004.
--
-- Tres detalles que no son negociables, con su motivo:
--
--   WHERE (estado = 'CONFIRMADA')  solo las confirmadas compiten por el bloque.
--       Es lo que hace que cancelar libere el horario (RN-05) sin borrar la
--       fila, conservando la traza de RN-08 y el dato del reporte de
--       cancelaciones.
--
--   '[)'  inicio incluido, fin excluido. Sin esto una reserva de 10:00-11:00
--       bloquearía la de 11:00-12:00 y los bloques contiguos dejarían de poder
--       reservarse.
--
--   tsrange sobre fecha + hora_*  la expresión es inmutable y por tanto
--       indexable. Con una variante con zona horaria, crear el índice falla.
--
-- Requiere btree_gist (infra/postgres/init/02-extensiones.sql): un índice GiST
-- no sabe comparar un bigint con '=' sin esa extensión.
ALTER TABLE reserva ADD CONSTRAINT reserva_sin_solape
    EXCLUDE USING gist (
        cancha_id WITH =,
        tsrange(fecha + hora_inicio, fecha + hora_fin, '[)') WITH &&
    ) WHERE (estado = 'CONFIRMADA');

-- Las dos consultas calientes: "mis reservas" y "qué ocupa esta cancha ese día".
CREATE INDEX reserva_por_usuario ON reserva (usuario_id, fecha);
CREATE INDEX reserva_por_cancha_fecha ON reserva (cancha_id, fecha);
