spring:
  application:
    name: ms-usuarios
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/usuarios_db}
    username: ${DB_USERNAME:usuarios_db_user}
    password: ${DB_PASSWORD:usuarios_db_pass}
  jpa:
    hibernate:
      # validate (no update): el esquema lo versiona Flyway. Ver taller, §4.1
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
